name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: macos
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
      - run: yarn install --frozen-lockfile

      - name: Build
        run: yarn docs:build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: "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"
          publish_dir: docs/.vitepress/dist

